<a href="https://colab.research.google.com/github/kszymon/neural-network/blob/main/03_keras%20/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Konfiguracja środowiska


In [36]:
# Przygotowanie środowiska do pracy z Tensorflow
# Jeśli otrzymasz błąd podczas instalacji Tensorflow uruchom tę komórkę raz jeszcze.

!pip uninstall -y tensorflow
!pip install -q tensorflow

Found existing installation: tensorflow 2.19.0
Uninstalling tensorflow-2.19.0:
  Successfully uninstalled tensorflow-2.19.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-decision-forests 1.11.0 requires tensorflow==2.18.0, but you have tensorflow 2.19.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.19.0 which is incompatible.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.19.0 which is incompatible.


In [37]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.19.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [38]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

<Sequential name=sequential_9, built=False>


Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [39]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda *.summary()*

In [40]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodanie kolejnej warstwy

In [41]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [42]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.737318 -2.737318
1 -2.546481 -2.546481
2 -2.544757 -2.544757
3 -2.469504 -2.469504
4 -2.429706 -2.429706

In [43]:
px.line(data, x='data', y='linear', width=800, range_y=[-2, 2])

In [44]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.737318  0.060807
1 -2.546481  0.072663
2 -2.544757  0.072779
3 -2.469504  0.078024
4 -2.429706  0.080935

In [45]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

In [46]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -2.737318   0.0
1 -2.546481   0.0
2 -2.544757   0.0
3 -2.469504   0.0
4 -2.429706   0.0

In [47]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

In [48]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -2.737318 -0.991651
1 -2.546481 -0.987795
2 -2.544757 -0.987753
3 -2.469504 -0.985778
4 -2.429706 -0.984609

In [49]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])

In [50]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [51]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [52]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [53]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [54]:
data[:3]

array([[ 6.04254883e-02, -1.38396146e-01, -1.39131248e+00,
         1.21506932e-01, -2.26465369e-01, -3.37685434e-01,
        -8.02890801e-01,  2.89158767e-01, -1.70082322e+00,
         4.34084077e-04, -1.11972501e+00,  2.19280359e-01,
         1.58826896e+00,  4.06108121e-01,  7.98446497e-01,
        -4.78541324e-01, -2.07325049e-01, -5.42489052e-01,
         2.58638221e-01,  6.76063194e-01,  6.59381867e-01,
        -8.39602656e-01,  8.82863302e-01, -2.35302318e+00,
         9.60470900e-01, -5.44691172e-01, -1.63070709e+00,
         8.98662903e-01,  8.29075991e-02,  8.43304595e-01,
        -1.43421938e-01, -4.40265053e-02, -6.52744080e-01,
         7.16403299e-01, -9.65983460e-01, -6.56054392e-01,
         2.65635080e-01,  1.50679646e-01, -1.36035186e+00,
        -1.33064241e+00, -5.02090164e-01,  3.95665065e-01,
        -9.26124870e-02, -9.61739633e-01,  9.04644484e-01,
         3.12847615e-01, -7.39674066e-01,  1.79710184e-01,
        -5.49722233e-02,  6.04700579e-01, -9.50625482e-0

In [55]:
labels[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [56]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.5140 - loss: 0.7878
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5758 - loss: 0.7038
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6091 - loss: 0.6698
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6495 - loss: 0.6304
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7074 - loss: 0.5902
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7127 - loss: 0.5740
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.5341
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7679 - loss: 0.5248
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7945 - loss: 0.4976
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8446 - loss: 0.4698
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8611 - loss: 0.4467
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8866 - 

In [57]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5137 - loss: 0.8304
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5825 - loss: 0.6969
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6175 - loss: 0.6433
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6484 - loss: 0.6048
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6992 - loss: 0.5667
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7574 - loss: 0.5372
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8100 - loss: 0.5038
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8208 - loss: 0.4743
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8610 - loss: 0.4479
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8603 - loss: 0.4306
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8976 - loss: 0.4038
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8950 - lo

In [58]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5046 - loss: 0.8320 - val_accuracy: 0.5050 - val_loss: 0.8272
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5676 - loss: 0.7151 - val_accuracy: 0.4650 - val_loss: 0.8208
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6034 - loss: 0.6700 - val_accuracy: 0.4700 - val_loss: 0.8185
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6795 - loss: 0.6044 - val_accuracy: 0.4750 - val_loss: 0.8195
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7101 - loss: 0.5875 - val_accuracy: 0.4750 - val_loss: 0.8204
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7415 - loss: 0.5529 - val_accuracy: 0.4850 - val_loss: 0.8225
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7787 - loss: 0.5233 - val_accuracy: 0.4750 - val_loss: 0.8250
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8000 - loss: 0.5123 - val_accuracy: 0.4650 - val_loss

In [59]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [60]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [61]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [62]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.5518 - loss: 0.7911 - val_accuracy: 0.4350 - val_loss: 0.8477
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5798 - loss: 0.7079 - val_accuracy: 0.4400 - val_loss: 0.8411
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6229 - loss: 0.6625 - val_accuracy: 0.4200 - val_loss: 0.8406
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6559 - loss: 0.6114 - val_accuracy: 0.4300 - val_loss: 0.8421
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6853 - loss: 0.5934 - val_accuracy: 0.4250 - val_loss: 0.8485
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5444 - val_accuracy: 0.4400 - val_loss: 0.8547
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7676 - loss: 0.5230 - val_accuracy: 0.4400 - val_loss: 0.8663
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.4941 - val_accuracy: 0.4200 - val_loss

In [63]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [64]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


array([[0.33668613],
       [0.12139373],
       [0.7854803 ],
       [0.2883198 ],
       [0.74830085]], dtype=float32)

In [65]:
#model.predict_proba(test_data)
predictions = (model.predict(test_data) > 0.5).astype("int32")
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[0]
 [0]
 [1]
 [0]
 [1]]


In [66]:
#model.predict_classes(test_data)

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [67]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1))

In [68]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [69]:
data[:3]

array([[0.29463046, 0.70425522, 0.45748441, 0.43890574, 0.83078247,
        0.70774732, 0.76768355, 0.28879853, 0.90966958, 0.46438526,
        0.50917017, 0.10777928, 0.25642619, 0.98804   , 0.61651025,
        0.98537027, 0.55392687, 0.67287037, 0.66335368, 0.7305007 ,
        0.89444622, 0.00864315, 0.29860453, 0.62400358, 0.35824513,
        0.15795762, 0.32558426, 0.312369  , 0.55458212, 0.97742375,
        0.54018445, 0.20011429, 0.48516877, 0.7769926 , 0.5801603 ,
        0.38569339, 0.56662516, 0.9601019 , 0.09197107, 0.9932368 ,
        0.90197594, 0.37318303, 0.88553801, 0.47932935, 0.49393451,
        0.01125403, 0.29001066, 0.84195321, 0.19994793, 0.61761975,
        0.63366052, 0.17026446, 0.40061734, 0.80326598, 0.15954614,
        0.49618025, 0.08423714, 0.49543918, 0.36037616, 0.64216593,
        0.16652929, 0.7917956 , 0.55862964, 0.21867704, 0.42568183,
        0.15064018, 0.73595393, 0.52595015, 0.03594907, 0.11529521,
        0.97981149, 0.22589799, 0.42974115, 0.74

In [70]:
labels[:10]

array([[2],
       [5],
       [7],
       [8],
       [6],
       [3],
       [6],
       [9],
       [2],
       [2]])

In [71]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [72]:
labels[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [73]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.0946 - loss: 2.3485 - val_accuracy: 0.1050 - val_loss: 2.3278
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1104 - loss: 2.3020 - val_accuracy: 0.0750 - val_loss: 2.3113
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1254 - loss: 2.2808 - val_accuracy: 0.1050 - val_loss: 2.3173
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1576 - loss: 2.2664 - val_accuracy: 0.0950 - val_loss: 2.3112
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1571 - loss: 2.2563 - val_accuracy: 0.0950 - val_loss: 2.3098
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1647 - loss: 2.2468 - val_accuracy: 0.0950 - val_loss: 2.3142
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2138 - loss: 2.2281 - val_accuracy: 0.0800 - val_loss: 2.3102
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1604 - loss: 2.2363 - val_accuracy: 0.0950 - val_loss

In [74]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step


array([[0.03425504, 0.0398978 , 0.19498155, 0.05838944, 0.31967944,
        0.12632053, 0.04817495, 0.07096439, 0.06363889, 0.04369806],
       [0.13548881, 0.01443007, 0.05528178, 0.0562338 , 0.21999831,
        0.04764811, 0.10914824, 0.08920479, 0.10405876, 0.1685072 ],
       [0.1667752 , 0.09659642, 0.02877249, 0.09820825, 0.09210087,
        0.09412614, 0.06718164, 0.13645226, 0.1041495 , 0.11563712],
       [0.15438886, 0.03907867, 0.02249274, 0.02420812, 0.23271322,
        0.112628  , 0.10165354, 0.14522746, 0.0264708 , 0.14113848],
       [0.07870306, 0.09787573, 0.15100543, 0.08848108, 0.09767834,
        0.08223394, 0.08274309, 0.08688173, 0.17879239, 0.05560519],
       [0.06943635, 0.13123694, 0.07572994, 0.06904623, 0.03269675,
        0.14837192, 0.13119766, 0.15433398, 0.13968353, 0.04826657],
       [0.10349421, 0.08741638, 0.07387715, 0.07032175, 0.09256006,
        0.14181055, 0.12044638, 0.12573078, 0.10922922, 0.07511348],
       [0.1659809 , 0.05913404, 0.0630899

In [81]:
#model.predict_classes(test_data)
predicted_digits = np.argmax(model.predict(test_data), axis=1)
print(predicted_digits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[4 4 0 4 8 7 5 0 4 8]


### <a name='a6'></a> Przykład - regresja

In [83]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [84]:
data[:3]

array([[0.33308049, 0.27670216, 0.31457508, 0.08421488, 0.05785828,
        0.281741  , 0.58434617, 0.94497654, 0.99024847, 0.58757645,
        0.50356192, 0.92002867, 0.56589137, 0.33152333, 0.42165933,
        0.4313212 , 0.91186371, 0.74663262, 0.35543171, 0.73063785,
        0.28854538, 0.91594531, 0.74918653, 0.28248261, 0.7382144 ,
        0.20740194, 0.12151527, 0.91410279, 0.76585435, 0.32197626,
        0.31842995, 0.02076874, 0.43361263, 0.1633066 , 0.04624053,
        0.72374103, 0.84977894, 0.72235041, 0.78313906, 0.33788786,
        0.82003481, 0.47667353, 0.70408158, 0.3376091 , 0.59713849,
        0.73595013, 0.64690519, 0.93550218, 0.92707844, 0.72167172,
        0.04925452, 0.16685032, 0.45851305, 0.85830927, 0.60922336,
        0.56939217, 0.36899928, 0.55653478, 0.47502597, 0.71129939,
        0.20045338, 0.5396943 , 0.79753726, 0.22632407, 0.92131247,
        0.33693865, 0.23740704, 0.80121426, 0.59700855, 0.55729528,
        0.99840874, 0.18531498, 0.12409588, 0.15

In [85]:
labels[:10]

array([42.22191356, 46.79224856,  0.96853202,  8.42791174, 17.48712186,
       38.7071942 , 11.33417078, 35.77409813, 45.72676393, 34.20379912])

In [86]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 584.2352 - val_loss: 333.2779
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 293.1638 - val_loss: 234.9258
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 218.4655 - val_loss: 230.9070
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 216.6644 - val_loss: 231.9227
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 218.1053 - val_loss: 231.2299
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 212.0619 - val_loss: 229.6788
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 214.6890 - val_loss: 230.1923
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 208.5279 - val_loss: 231.2715
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 208.5361 - val_loss: 231.4624
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 209.6788 - val_loss: 231.4528
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 204.0641 - val_loss: 231.0797
Epoch 12/30
25/25 ━━━━━━━━━━━

In [87]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 22.1658 - mse: 693.1337 - val_loss: 16.4397 - val_mse: 422.7593
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.4620 - mse: 393.5874 - val_loss: 13.6606 - val_mse: 270.6883
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.2305 - mse: 241.3481 - val_loss: 13.1197 - val_mse: 228.8377
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.2547 - mse: 229.2498 - val_loss: 13.2357 - val_mse: 229.4360
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.5532 - mse: 211.9906 - val_loss: 13.2658 - val_mse: 230.0704
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6208 - mse: 215.4439 - val_loss: 13.2931 - val_mse: 230.7498
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6097 - mse: 210.5890 - val_loss: 13.2509 - val_mse: 229.8151
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.9189 - mse: 220.6504 - val_loss: 13.1821 - val_mse: 228.7946
Epoch 9/30
25/25 ━━━━━━

In [88]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[23.039114],
       [25.2528  ],
       [26.624416],
       [23.848866],
       [26.15182 ],
       [27.181953],
       [24.829754],
       [23.794842],
       [24.654478],
       [24.049438]], dtype=float32)