<a href="https://colab.research.google.com/github/kszymon/neural-network/blob/main/02_basics%20/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$

In [3]:
def max_relu(x):
    return max(x, 0.0)

In [4]:
for i in [-10., -5., 0., 5., 10. ]:
  print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [5]:
data = np.random.randn(50)
data = sorted(data)
data

[np.float64(-2.5132573845050388),
 np.float64(-1.4286760461783954),
 np.float64(-1.4199247411942029),
 np.float64(-1.396254444435322),
 np.float64(-1.3518507077143584),
 np.float64(-1.3131223457284675),
 np.float64(-1.2803700081989542),
 np.float64(-1.2149414251265815),
 np.float64(-1.065987528499196),
 np.float64(-0.9634057153793258),
 np.float64(-0.9598407480917408),
 np.float64(-0.9126688633059468),
 np.float64(-0.8115245157352857),
 np.float64(-0.6884703309976942),
 np.float64(-0.5066589915181166),
 np.float64(-0.4395872106177178),
 np.float64(-0.4130611814152835),
 np.float64(-0.39089735188938923),
 np.float64(-0.38560253399476335),
 np.float64(-0.37111191603440186),
 np.float64(-0.29206052425306517),
 np.float64(-0.28134883859784815),
 np.float64(-0.19885023992766335),
 np.float64(-0.048106338852007026),
 np.float64(-0.04116561377691787),
 np.float64(-0.034903521864009926),
 np.float64(-0.019497106979252665),
 np.float64(0.0405832722603997),
 np.float64(0.06523978639939004),
 np.

In [6]:
# wygenerowanie dancych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.040583, 0.06524 , 0.080524,
       0.182449, 0.24005 , 0.260145, 0.364861, 0.414391, 0.606003,
       0.639445, 0.711327, 0.748796, 0.762987, 0.807905, 0.810188,
       1.096687, 1.299618, 1.319608, 1.406559, 1.600129, 1.634669,
       2.062221, 2.641016])

In [7]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.513257            0.0
1 -1.428676            0.0
2 -1.419925            0.0
3 -1.396254            0.0
4 -1.351851            0.0

In [8]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLu Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [9]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [10]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
  print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [11]:
data = 3*np.random.randn(50)
data = sorted(data)
data

[np.float64(-7.436326894378295),
 np.float64(-5.899470003546683),
 np.float64(-5.8241837857355065),
 np.float64(-5.5843079678452066),
 np.float64(-5.517127999788401),
 np.float64(-5.0683282640314165),
 np.float64(-4.952976643891716),
 np.float64(-3.329821000892304),
 np.float64(-3.2437034822419335),
 np.float64(-3.239498024512052),
 np.float64(-3.0642975176716645),
 np.float64(-3.0513836469396507),
 np.float64(-3.0402642291570645),
 np.float64(-2.415115251521196),
 np.float64(-2.364706261441275),
 np.float64(-1.6620468922039386),
 np.float64(-1.184708211390979),
 np.float64(-0.8486370007358917),
 np.float64(-0.5421789797073389),
 np.float64(-0.5137488027067192),
 np.float64(-0.41015437100987195),
 np.float64(-0.40730938161607444),
 np.float64(-0.22283767841239263),
 np.float64(4.22669140575089e-06),
 np.float64(0.08526680599240188),
 np.float64(0.09488387741217069),
 np.float64(0.10022010562189985),
 np.float64(0.3164422678302006),
 np.float64(0.3276637331386122),
 np.float64(0.3364688

In [12]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[np.float64(0.0005890990824120063),
 np.float64(0.0027334051174656713),
 np.float64(0.0029465076926096898),
 np.float64(0.0037422910354857203),
 np.float64(0.0040012945969697036),
 np.float64(0.006253578133507655),
 np.float64(0.007012828405754442),
 np.float64(0.034562202569471366),
 np.float64(0.03755380414789483),
 np.float64(0.03770610013686455),
 np.float64(0.044604206912704655),
 np.float64(0.04515777507181656),
 np.float64(0.045639660457305574),
 np.float64(0.08202732118979289),
 np.float64(0.08590391704988137),
 np.float64(0.15948741734217745),
 np.float64(0.23420670355328244),
 np.float64(0.2997188558670805),
 np.float64(0.36768084179410315),
 np.float64(0.37431513067289857),
 np.float64(0.39887510645703655),
 np.float64(0.39955745610073756),
 np.float64(0.44451996990054327),
 np.float64(0.5000010566728514),
 np.float64(0.5213037957520666),
 np.float64(0.5237031888018121),
 np.float64(0.5250340762453503),
 np.float64(0.5784569617089114),
 np.float64(0.5811908187832603),
 np.fl

In [13]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -7.436327      0.000589
1 -5.899470      0.002733
2 -5.824184      0.002947
3 -5.584308      0.003742
4 -5.517128      0.004001

In [14]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [15]:
def tanh(x):
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [16]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[np.float64(-4.842781786462882),
 np.float64(-4.7337073771832925),
 np.float64(-4.589623442826718),
 np.float64(-4.173026030078552),
 np.float64(-3.6081577093205057),
 np.float64(-3.3613968255134363),
 np.float64(-2.983223895265748),
 np.float64(-2.9403824128539178),
 np.float64(-2.822425365955312),
 np.float64(-2.7524068522283094),
 np.float64(-2.6921032036929384),
 np.float64(-2.4530114455212684),
 np.float64(-2.2268749701866235),
 np.float64(-2.1850381575187567),
 np.float64(-2.152186807085846),
 np.float64(-2.1054348642513245),
 np.float64(-2.045574192573764),
 np.float64(-1.9529376841227362),
 np.float64(-1.9243669005059774),
 np.float64(-1.7360920421033579),
 np.float64(-1.6725718551260378),
 np.float64(-1.6039610987908701),
 np.float64(-1.471217845716012),
 np.float64(-1.464993041413583),
 np.float64(-1.4504821897392426),
 np.float64(-1.3902570393962976),
 np.float64(-1.382117469269435),
 np.float64(-1.3305699893482854),
 np.float64(-1.274623164532725),
 np.float64(-1.2276963147

In [17]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[np.float64(-0.9998756584775639),
 np.float64(-0.999845349821078),
 np.float64(-0.9997937048933946),
 np.float64(-0.9995254493411783),
 np.float64(-0.9985320706435297),
 np.float64(-0.9975965472256096),
 np.float64(-0.99488644622246),
 np.float64(-0.9944302571970288),
 np.float64(-0.9929535616730567),
 np.float64(-0.9918986569436015),
 np.float64(-0.9908649554480556),
 np.float64(-0.9853050343845401),
 np.float64(-0.976997915814591),
 np.float64(-0.9750155104171866),
 np.float64(-0.9733414496440869),
 np.float64(-0.9707667076372148),
 np.float64(-0.9671098804955909),
 np.float64(-0.9605472577025264),
 np.float64(-0.9582756131357504),
 np.float64(-0.9397717502953333),
 np.float64(-0.9318908998882007),
 np.float64(-0.92226263503583),
 np.float64(-0.8998095160115269),
 np.float64(-0.8986180107176998),
 np.float64(-0.8957881781133056),
 np.float64(-0.8832274271063011),
 np.float64(-0.8814245385237154),
 np.float64(-0.869388572732582),
 np.float64(-0.8550457320710954),
 np.float64(-0.841909

In [18]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.842782  -0.999876
1 -4.733707  -0.999845
2 -4.589623  -0.999794
3 -4.173026  -0.999525
4 -3.608158  -0.998532

In [19]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [25]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [26]:
data = np.random.randn(4, 5)
data

array([[-0.258013,  1.064123, -0.084627, -0.082136,  0.287008],
       [-1.365746,  0.767606, -0.49374 ,  0.380337,  1.877598],
       [-0.304974, -1.05998 ,  1.481891,  0.509745, -1.247254],
       [ 1.631192, -0.297565, -0.951955, -0.767908, -0.545189]])

In [27]:
result = softmax(data)
result

array([[0.112896, 0.423522, 0.13427 , 0.134605, 0.194706],
       [0.023156, 0.195505, 0.055381, 0.13273 , 0.593228],
       [0.099118, 0.046586, 0.591804, 0.223862, 0.03863 ],
       [0.701697, 0.101977, 0.053003, 0.063714, 0.079609]])

In [28]:
result.sum(axis=1)

array([1., 1., 1., 1.])